version: '2'
services:
  worker:
    image: worker
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      - LANG=en_US.utf8

  tests:
    extends: worker
    image: worker-tests